In [1]:
import numpy as np 
X = np.array(([2, 9], [1, 5], [3, 6]), dtype=float) # Features ( Hrs Slept, Hrs Studied)
y = np.array(([92], [86], [89]), dtype=float) # Labels(Marks obtained)
c=np.amax(X,axis=0) # Normalize
print(c)
X = X/c # Normalize
y = y/100
print(X)
print(y)

def sigmoid(x):
    return 1/(1 + np.exp(-x))
def sigmoid_grad(x):
    return x * (1 - x)

 # Variable initialization
epoch=1000 #Setting training iterations
eta =0.1 #Setting learning rate (eta)
input_neurons = 2 #number of features in data set
hidden_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer
# Weight and bias - Random initialization
wh=np.random.uniform(size=(input_neurons,hidden_neurons)) # 2x3
print(wh)
bh=np.random.uniform(size=(1,hidden_neurons)) # 1x3
print(bh)
wout=np.random.uniform(size=(hidden_neurons,output_neurons)) # 3x1
print(wout)
bout=np.random.uniform(size=(1,output_neurons))
print(bout)

for i in range(epoch):
    #Forward Propogation
    h_ip=np.dot(X,wh) + bh # Dot product + bias
    print(h_ip)
    h_act = sigmoid(h_ip) # Activation function
    o_ip=np.dot(h_act,wout) + bout
    output = sigmoid(o_ip)

 #Backpropagation
 # Error at Output layer
    Eo = y-output # Error at o/p
    outgrad = sigmoid_grad(output)
    d_output = Eo* outgrad # Errj=Oj(1-Oj)(Tj-Oj)
    print("the d_output is",d_output)

# Error at Hidden later
    Eh = d_output.dot(wout.T) # .T means transpose
    hiddengrad = sigmoid_grad(h_act) # How much hidden layer wts contributed to error
    d_hidden = Eh * hiddengrad
    wout += h_act.T.dot(d_output) *eta # Dotproduct of nextlayererror and currentlayerop
    wh += X.T.dot(d_hidden) *eta

print("Normalized Input: \n" + str(X))
print("Actual Output: \n" + str(y))
print("Predicted Output: \n" ,output)

[3. 9.]
[[0.66666667 1.        ]
 [0.33333333 0.55555556]
 [1.         0.66666667]]
[[0.92]
 [0.86]
 [0.89]]
[[0.09740839 0.60782321 0.96105228]
 [0.65673586 0.39322162 0.9330507 ]]
[[0.80712547 0.69938257 0.46604127]]
[[0.70791917]
 [0.08518705]
 [0.18917482]]
[[0.25758366]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.3047535

[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.4978

[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.49781966 2.03979348]
 [1.20444819 1.12044676 1.30475352]
 [1.34235776 1.56935352 2.04912734]]
[[1.52880025 1.4978